### ISSUE TITLE
Could not load file or assembly GroupDocs.Editor, Version=21.1.1.0

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-editor/GroupDocs.Editor-for-.NET-WebForms#15]
Hi,
Please have a look at the exception/error details in the attached text file. Screencasts are sent to you via email. Following [these](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-WebForms/issues/61) steps didn't help. 
Please let me know if you need any further details. 
Thanks 

[error.txt](https://github.com/groupdocs-editor/GroupDocs.Editor-for-.NET-WebForms/files/6048925/error.txt)

**Comment by bobkovalex** [comment]
Hi @atirtahirgroupdocs 

The issue is being investigated.
Thanks.

**Comment by Pavel-Teplitsky** [comment]
Hi @atirtahirgroupdocs 

We have fixed a sample build issue (issue shown on the first screencast shared by you). Please pull the latest updates from the master branch. 
As for the issue from the second screencast: unfortunately we were not able to reproduce it. We followed steps described on the forum thread and all works well. It would be very useful and helpful if user can prepare and share some test app on which this issue is reproducible.

Best regards.
